export enum DeliveryStatus {
  CREATED = "CREATED",
  PICKED_UP_BY_COURIER = "PICKED_UP_BY_COURIER",
  RECEIVED_IN_FACILITY = "RECEIVED_IN_FACILITY",
  SENT_FROM_FACILITY = "SENT_FROM_FACILITY",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERY_SUCCEED = "DELIVERY_SUCCEED",
  DELIVERY_FAILED = "DELIVERY_FAILED",
  WAITING_IN_PICKUP_POINT = "WAITING_IN_PICKUP_POINT",
  ON_THE_WAY_BACK_TO_SENDER = "ON_THE_WAY_BACK_TO_SENDER",
  RETURNED = "RETURNED",
}
